# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    org.springframework.r2dbc: DEBUG
    com.usco.demo.stock: DEBUG
    org.springframework.data.r2dbc: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev
    url: jdbc:mariadb://localhost:3306/uscodemestock
    user: root
    password: rootpassword
    change-log: classpath:/config/liquibase/master.xml
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/uscodemestock
    username: root
    password: rootpassword
    pool:
      max-size: 10
      initial-size: 5
      max-idle-time: 1
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8080
# ===================================================================

application:
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: 999j8ia4SzcWf2S04oB/5kmvwgbmgnqNiAu1z5bZgClgcAJfHKa85vjKmMDP1DIKBYrZ/V11D8kNB/b4uivZBv4xOnhR1Q7utHsCRlFSxxutvf7M636nCwAEIsxJiqGiyl85M95rHSusbv+A5WZVRCRW/6SEYkSS6B2nshkjI2U=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    use-json-format: false # By default, logs are not in Json format

springdoc:
  swagger-ui:
    path: /swagger-doc/swagger-ui.html